name: All Contributors

on:
  pull_request:
    types: [opened, closed]

jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Hall of Fame
        uses: all-contributors/all-contributors-action@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add: 'true'
